// Generated by gencpp from file agv_bringup/ShutdownRequest.msg
// DO NOT EDIT!


#ifndef AGV_BRINGUP_MESSAGE_SHUTDOWNREQUEST_H
#define AGV_BRINGUP_MESSAGE_SHUTDOWNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_bringup
{
template <class ContainerAllocator>
struct ShutdownRequest_
{
  typedef ShutdownRequest_<ContainerAllocator> Type;

  ShutdownRequest_()
    : flag(false)  {
    }
  ShutdownRequest_(const ContainerAllocator& _alloc)
    : flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::agv_bringup::ShutdownRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_bringup::ShutdownRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ShutdownRequest_

typedef ::agv_bringup::ShutdownRequest_<std::allocator<void> > ShutdownRequest;

typedef boost::shared_ptr< ::agv_bringup::ShutdownRequest > ShutdownRequestPtr;
typedef boost::shared_ptr< ::agv_bringup::ShutdownRequest const> ShutdownRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_bringup::ShutdownRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_bringup::ShutdownRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_bringup::ShutdownRequest_<ContainerAllocator1> & lhs, const ::agv_bringup::ShutdownRequest_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_bringup::ShutdownRequest_<ContainerAllocator1> & lhs, const ::agv_bringup::ShutdownRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_bringup::ShutdownRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_bringup::ShutdownRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_bringup::ShutdownRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_bringup::ShutdownRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_bringup::ShutdownRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_bringup::ShutdownRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_bringup::ShutdownRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24842bc754e0f5cc982338eca1269251";
  }

  static const char* value(const ::agv_bringup::ShutdownRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24842bc754e0f5ccULL;
  static const uint64_t static_value2 = 0x982338eca1269251ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_bringup::ShutdownRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_bringup/ShutdownRequest";
  }

  static const char* value(const ::agv_bringup::ShutdownRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_bringup::ShutdownRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool flag\n"
;
  }

  static const char* value(const ::agv_bringup::ShutdownRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_bringup::ShutdownRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShutdownRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_bringup::ShutdownRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_bringup::ShutdownRequest_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_BRINGUP_MESSAGE_SHUTDOWNREQUEST_H
