// Generated by gencpp from file agv_bringup/Shutdown.msg
// DO NOT EDIT!


#ifndef AGV_BRINGUP_MESSAGE_SHUTDOWN_H
#define AGV_BRINGUP_MESSAGE_SHUTDOWN_H

#include <ros/service_traits.h>


#include <agv_bringup/ShutdownRequest.h>
#include <agv_bringup/ShutdownResponse.h>


namespace agv_bringup
{

struct Shutdown
{

typedef ShutdownRequest Request;
typedef ShutdownResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Shutdown
} // namespace agv_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_bringup::Shutdown > {
  static const char* value()
  {
    return "2646f2e0845a85576ebb6b81e48a6f75";
  }

  static const char* value(const ::agv_bringup::Shutdown&) { return value(); }
};

template<>
struct DataType< ::agv_bringup::Shutdown > {
  static const char* value()
  {
    return "agv_bringup/Shutdown";
  }

  static const char* value(const ::agv_bringup::Shutdown&) { return value(); }
};


// service_traits::MD5Sum< ::agv_bringup::ShutdownRequest> should match
// service_traits::MD5Sum< ::agv_bringup::Shutdown >
template<>
struct MD5Sum< ::agv_bringup::ShutdownRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_bringup::Shutdown >::value();
  }
  static const char* value(const ::agv_bringup::ShutdownRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_bringup::ShutdownRequest> should match
// service_traits::DataType< ::agv_bringup::Shutdown >
template<>
struct DataType< ::agv_bringup::ShutdownRequest>
{
  static const char* value()
  {
    return DataType< ::agv_bringup::Shutdown >::value();
  }
  static const char* value(const ::agv_bringup::ShutdownRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_bringup::ShutdownResponse> should match
// service_traits::MD5Sum< ::agv_bringup::Shutdown >
template<>
struct MD5Sum< ::agv_bringup::ShutdownResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_bringup::Shutdown >::value();
  }
  static const char* value(const ::agv_bringup::ShutdownResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_bringup::ShutdownResponse> should match
// service_traits::DataType< ::agv_bringup::Shutdown >
template<>
struct DataType< ::agv_bringup::ShutdownResponse>
{
  static const char* value()
  {
    return DataType< ::agv_bringup::Shutdown >::value();
  }
  static const char* value(const ::agv_bringup::ShutdownResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_BRINGUP_MESSAGE_SHUTDOWN_H
